version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    labels:
      - "kind/dependencies"

  - package-ecosystem: 'npm'
    directory: '/website'
    schedule:
      interval: 'monthly'
    labels:
      - "kind/dependencies"

  - package-ecosystem: 'npm'
    directory: '/packages/jellyfish'
    schedule:
      interval: 'weekly'
    labels:
      - "kind/dependencies"
    ignore:
      - dependency-name: "parcel"
      - dependency-name: "@parcel/*"
      - dependency-name: "@defichain/*"

  - package-ecosystem: 'npm'
    directory: '/packages/jellyfish-core'
    schedule:
      interval: 'weekly'
    labels:
      - "kind/dependencies"
    ignore:
      - dependency-name: "@defichain/*"

  - package-ecosystem: 'npm'
    directory: '/packages/jellyfish-jsonrpc'
    schedule:
      interval: 'weekly'
    labels:
      - "kind/dependencies"
    ignore:
      - dependency-name: "@defichain/*"

  - package-ecosystem: 'npm'
    directory: '/packages/testcontainers'
    schedule:
      interval: 'weekly'
    labels:
      - "kind/dependencies"
    ignore:
      - dependency-name: "@defichain/*"
