name: Bump Dependencies

on:
  workflow_dispatch:
  schedule:
    - cron: '0 1 * * *'

jobs:
  nestjs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
      - uses: actions/setup-node@2fddd8803e2f5c9604345a0b591c3020ee971a93
        with:
          node-version: '16'
          cache: 'npm'

      - run: npx npm-check-updates --deep -l m -u -f "/^@nestjs\/.+/"

      - name: Upgrade dependencies
        run: |
          if ! git diff-index --quiet HEAD; then
            npm i
          else
            echo "no file has been changed"
          fi

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@923ad837f191474af6b1721408744feb989a4c27
        with:
          token: ${{ secrets.JELLYFISHSDK_BOT_GITHUB_TOKEN }}
          labels: kind/dependencies
          commit-message: "bump(deps): bump @nestjs/*"
          committer: JellyfishSDK Bot <bots+github-jellyfish@birthday.dev>
          author: JellyfishSDK Bot <bots+github-jellyfish@birthday.dev>
          title: "bump(deps): bump @nestjs/*"
          body: |
            #### What this PR does / why we need it:
            Bump `@nestjs/*` dependencies to the newest release.
          branch: jellyfishsdk-bot/bump-nestjs-deps


  docusaurus:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
      - uses: actions/setup-node@2fddd8803e2f5c9604345a0b591c3020ee971a93
        with:
          node-version: '16'
          cache: 'npm'

      - run: npx npm-check-updates --deep -l m -u -f "/^@docusaurus\/.+/"

      - name: Upgrade dependencies
        run: |
          if ! git diff-index --quiet HEAD; then
            npm i
          else
            echo "no file has been changed"
          fi

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@923ad837f191474af6b1721408744feb989a4c27
        with:
          token: ${{ secrets.JELLYFISHSDK_BOT_GITHUB_TOKEN }}
          labels: kind/dependencies
          commit-message: "bump(deps): bump @docusaurus/*"
          committer: JellyfishSDK Bot <bots+github-jellyfish@birthday.dev>
          author: JellyfishSDK Bot <bots+github-jellyfish@birthday.dev>
          title: "bump(deps): bump @docusaurus/*"
          body: |
            #### What this PR does / why we need it:
            Bump `@docusaurus/*` dependencies to the newest release.
          branch: jellyfishsdk-bot/bump-docusaurus-deps